use_frameworks!

target 'RaveSDK_Example' do
  pod 'RaveSDK', :path => '../'
  pod 'Alamofire'
  pod 'lottie-ios','~>3.0.2'
  pod 'IQKeyboardManagerSwift'
  target 'RaveSDK_Tests' do
    inherit! :search_paths

    
  end
end
